export function climateSuggestion(weatherMain) {
  const climateMap = {
    Clear: [
      "park",
      "garden",
      "botanical_garden",
      "beach",
      "islands",
      "waterfalls",
      "nature_reserves",
      "mountain",
      "viewpoint",
      "picnic",
      "zoo",
      "amusement_park",
      "theme_park",
      "outdoor",
      "natural",
      "walking_area",
      "hiking",
      "river",
      "lake",
    ],

    Clouds: [
      "cafe",
      "restaurant",
      "bar",
      "pub",
      "bakery",
      "market",
      "square",
      "plaza",
      "street_food",
      "mall",
      "interesting_places",
      "cultural",
      "urban_environment",
    ],

    Rain: [
      "museum",
      "art_gallery",
      "cinema",
      "theatre",
      "concert_hall",
      "opera",
      "library",
      "mall",
      "shopping",
      "aquarium",
      "planetarium",
      "cultural",
      "indoor",
      "exhibition",
      "heritage",
    ],

    Thunderstorm: [
      "museum",
      "cinema",
      "mall",
      "cafe",
      "restaurant",
      "art_gallery",
      "library",
      "theatre",
      "indoor",
      "cultural",
      "entertainment",
    ],

    Snow: [
      "museum",
      "mall",
      "cafe",
      "theatre",
      "winter_sports",
      "skiing",
      "ice_rink",
      "spa",
      "sauna",
      "restaurant",
      "indoor",
      "cultural",
    ],
  };

  return climateMap[weatherMain] || ["interesting_places"];
}
